// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGi6p2Y6X0men_o4LwjkwLQo__zNGPqVE',
    appId: '1:574614288610:web:29fa030ffa67d8f2d6c6bb',
    messagingSenderId: '574614288610',
    projectId: 'protosem-forge',
    authDomain: 'protosem-forge.firebaseapp.com',
    storageBucket: 'protosem-forge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyqj5flocVg6Oa2c9aPU4iNio5gQcElkE',
    appId: '1:574614288610:android:be007d7ff901491ed6c6bb',
    messagingSenderId: '574614288610',
    projectId: 'protosem-forge',
    storageBucket: 'protosem-forge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OjmgaHQesPv1zoOcBGY2yu12Q9lSCTI',
    appId: '1:574614288610:ios:5d099544a4e39b8dd6c6bb',
    messagingSenderId: '574614288610',
    projectId: 'protosem-forge',
    storageBucket: 'protosem-forge.appspot.com',
    iosClientId: '574614288610-8mn9v4iv4g4sosb1droim94870682bfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.protosem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2OjmgaHQesPv1zoOcBGY2yu12Q9lSCTI',
    appId: '1:574614288610:ios:5d099544a4e39b8dd6c6bb',
    messagingSenderId: '574614288610',
    projectId: 'protosem-forge',
    storageBucket: 'protosem-forge.appspot.com',
    iosClientId: '574614288610-8mn9v4iv4g4sosb1droim94870682bfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.protosem',
  );
}
